export const ACCOUNT = [
  {
    id: "1",
    name: "ABC",
    avatar: `profile/1.jpg`,
    link: "localhost:3000/profile/1.html",
    isPublic: true,
    about:
      "Phasellus lacus justo, sodales sed maximus et, condimentum et neque. Quisque sed purus vel quam ullamcorper luctus. Nunc vel augue sapien. Suspendisse dignissim ipsum quis nunc vestibulum venenatis. Mauris non diam et mauris fringilla hendrerit. Proin id porta lectus. Curabitur vel porta eros. Sed suscipit malesuada tellus, id fringilla libero porttitor id. Proin imperdiet orci eget felis commodo, eu fermentum nibh elementum. Aenean sagittis nibh a risus imperdiet interdum. Suspendisse eget leo et metus consequat tempor sed nec eros. ",
    extra: {
      location: "Atlantis",
      email: "dummy@business.com",
      social: "Facebook",
      mentioned: "other account",
    },
    followers: ["2"],
    following: ["2"],
  },
  {
    id: "2",
    name: "DEF",
    avatar: `profile/2.jpg`,
    link: "localhost:3000/profile/2.html",
    isPublic: true,
    about:
      "Phasellus lacus justo, sodales sed maximus et, condimentum et neque. Quisque sed purus vel quam ullamcorper luctus. Nunc vel augue sapien. Suspendisse dignissim ipsum quis nunc vestibulum venenatis. Mauris non diam et mauris fringilla hendrerit. Proin id porta lectus. Curabitur vel porta eros. Sed suscipit malesuada tellus, id fringilla libero porttitor id. Proin imperdiet orci eget felis commodo, eu fermentum nibh elementum. Aenean sagittis nibh a risus imperdiet interdum. Suspendisse eget leo et metus consequat tempor sed nec eros. ",
    extra: {
      location: "Atlantis",
      email: "dummy@business.com",
      social: "Facebook",
      mentioned: "other account",
    },
    followers: ["1", "3", "4", "5", "6", "7", "8", "9"],
    following: ["1", "3", "4", "5", "6", "7", "8", "9"],
  },
  {
    id: "3",
    name: "EFG",
    avatar: `profile/3.jpg`,
    link: "localhost:3000/profile/3.html",
    isPublic: true,
    about:
      "Phasellus lacus justo, sodales sed maximus et, condimentum et neque. Quisque sed purus vel quam ullamcorper luctus. Nunc vel augue sapien. Suspendisse dignissim ipsum quis nunc vestibulum venenatis. Mauris non diam et mauris fringilla hendrerit. Proin id porta lectus. Curabitur vel porta eros. Sed suscipit malesuada tellus, id fringilla libero porttitor id. Proin imperdiet orci eget felis commodo, eu fermentum nibh elementum. Aenean sagittis nibh a risus imperdiet interdum. Suspendisse eget leo et metus consequat tempor sed nec eros. ",
    extra: {
      location: "Atlantis",
      email: "dummy@business.com",
      social: "Facebook",
      mentioned: "other account",
    },
    followers: ["2"],
    following: ["2"],
  },
  {
    id: "4",
    name: "HIJ",
    avatar: `profile/4.jpg`,
    link: "localhost:3000/profile/4.html",
    isPublic: true,
    about:
      "Phasellus lacus justo, sodales sed maximus et, condimentum et neque. Quisque sed purus vel quam ullamcorper luctus. Nunc vel augue sapien. Suspendisse dignissim ipsum quis nunc vestibulum venenatis. Mauris non diam et mauris fringilla hendrerit. Proin id porta lectus. Curabitur vel porta eros. Sed suscipit malesuada tellus, id fringilla libero porttitor id. Proin imperdiet orci eget felis commodo, eu fermentum nibh elementum. Aenean sagittis nibh a risus imperdiet interdum. Suspendisse eget leo et metus consequat tempor sed nec eros. ",
    extra: {
      location: "Atlantis",
      email: "dummy@business.com",
      social: "Facebook",
      mentioned: "other account",
    },
    followers: ["2"],
    following: ["2"],
  },
  {
    id: "5",
    name: "KLM",
    avatar: `profile/5.jpg`,
    link: "localhost:3000/profile/5.html",
    isPublic: false,
    about:
      "Phasellus lacus justo, sodales sed maximus et, condimentum et neque. Quisque sed purus vel quam ullamcorper luctus. Nunc vel augue sapien. Suspendisse dignissim ipsum quis nunc vestibulum venenatis. Mauris non diam et mauris fringilla hendrerit. Proin id porta lectus. Curabitur vel porta eros. Sed suscipit malesuada tellus, id fringilla libero porttitor id. Proin imperdiet orci eget felis commodo, eu fermentum nibh elementum. Aenean sagittis nibh a risus imperdiet interdum. Suspendisse eget leo et metus consequat tempor sed nec eros. ",
    extra: {
      location: "Atlantis",
      email: "dummy@business.com",
      social: "Facebook",
      mentioned: "other account",
    },
    followers: ["2"],
    following: ["2"],
  },
  {
    id: "6",
    name: "NOP",
    avatar: `profile/6.jpg`,
    link: "localhost:3000/profile/6.html",
    isPublic: false,
    about:
      "Phasellus lacus justo, sodales sed maximus et, condimentum et neque. Quisque sed purus vel quam ullamcorper luctus. Nunc vel augue sapien. Suspendisse dignissim ipsum quis nunc vestibulum venenatis. Mauris non diam et mauris fringilla hendrerit. Proin id porta lectus. Curabitur vel porta eros. Sed suscipit malesuada tellus, id fringilla libero porttitor id. Proin imperdiet orci eget felis commodo, eu fermentum nibh elementum. Aenean sagittis nibh a risus imperdiet interdum. Suspendisse eget leo et metus consequat tempor sed nec eros. ",
    extra: {
      location: "Atlantis",
      email: "dummy@business.com",
      social: "Facebook",
      mentioned: "other account",
    },
    followers: ["2"],
    following: ["2"],
  },
  {
    id: "7",
    name: "NOP",
    avatar: `profile/7.jpg`,
    link: "localhost:3000/profile/7.html",
    isPublic: false,
    about:
      "Phasellus lacus justo, sodales sed maximus et, condimentum et neque. Quisque sed purus vel quam ullamcorper luctus. Nunc vel augue sapien. Suspendisse dignissim ipsum quis nunc vestibulum venenatis. Mauris non diam et mauris fringilla hendrerit. Proin id porta lectus. Curabitur vel porta eros. Sed suscipit malesuada tellus, id fringilla libero porttitor id. Proin imperdiet orci eget felis commodo, eu fermentum nibh elementum. Aenean sagittis nibh a risus imperdiet interdum. Suspendisse eget leo et metus consequat tempor sed nec eros. ",
    extra: {
      location: "Atlantis",
      email: "dummy@business.com",
      social: "Facebook",
      mentioned: "other account",
    },
    followers: ["2"],
    following: ["2"],
  },
  {
    id: "8",
    name: "NOP",
    avatar: `profile/8.jpg`,
    link: "localhost:3000/profile/8.html",
    isPublic: false,
    about:
      "Phasellus lacus justo, sodales sed maximus et, condimentum et neque. Quisque sed purus vel quam ullamcorper luctus. Nunc vel augue sapien. Suspendisse dignissim ipsum quis nunc vestibulum venenatis. Mauris non diam et mauris fringilla hendrerit. Proin id porta lectus. Curabitur vel porta eros. Sed suscipit malesuada tellus, id fringilla libero porttitor id. Proin imperdiet orci eget felis commodo, eu fermentum nibh elementum. Aenean sagittis nibh a risus imperdiet interdum. Suspendisse eget leo et metus consequat tempor sed nec eros. ",
    extra: {
      location: "Atlantis",
      email: "dummy@business.com",
      social: "Facebook",
      mentioned: "other account",
    },
    followers: ["2"],
    following: ["2"],
  },
  {
    id: "9",
    name: "NOP",
    avatar: `profile/9.jpg`,
    link: "localhost:3000/profile/9.html",
    isPublic: false,
    about:
      "Phasellus lacus justo, sodales sed maximus et, condimentum et neque. Quisque sed purus vel quam ullamcorper luctus. Nunc vel augue sapien. Suspendisse dignissim ipsum quis nunc vestibulum venenatis. Mauris non diam et mauris fringilla hendrerit. Proin id porta lectus. Curabitur vel porta eros. Sed suscipit malesuada tellus, id fringilla libero porttitor id. Proin imperdiet orci eget felis commodo, eu fermentum nibh elementum. Aenean sagittis nibh a risus imperdiet interdum. Suspendisse eget leo et metus consequat tempor sed nec eros. ",
    extra: {
      location: "Atlantis",
      email: "dummy@business.com",
      social: "Facebook",
      mentioned: "other account",
    },
    followers: ["2"],
    following: ["2"],
  },
];
