export const ACCOUNT = [
  {
    id: "1",
    name: "ABC",
    avatar: `profile/1.jpg`,
    link: "localhost:3000/profile/1.html",
    isPublic: true,
  },
  {
    id: "2",
    name: "DEF",
    avatar: `profile/2.jpg`,
    link: "localhost:3000/profile/2.html",
    isPublic: true,
  },
  {
    id: "3",
    name: "EFG",
    avatar: `profile/3.jpg`,
    link: "localhost:3000/profile/3.html",
    isPublic: true,
  },
  {
    id: "4",
    name: "HIJ",
    avatar: `profile/4.jpg`,
    link: "localhost:3000/profile/4.html",
    isPublic: true,
  },
  {
    id: "5",
    name: "KLM",
    avatar: `profile/5.jpg`,
    link: "localhost:3000/profile/5.html",
    isPublic: false,
  },
  {
    id: "6",
    name: "NOP",
    avatar: `profile/6.jpg`,
    link: "localhost:3000/profile/6.html",
    isPublic: false,
  },
  {
    id: "7",
    name: "NOP",
    avatar: `profile/7.jpg`,
    link: "localhost:3000/profile/7.html",
    isPublic: false,
  },
  {
    id: "8",
    name: "NOP",
    avatar: `profile/8.jpg`,
    link: "localhost:3000/profile/8.html",
    isPublic: false,
  },
  {
    id: "9",
    name: "NOP",
    avatar: `profile/9.jpg`,
    link: "localhost:3000/profile/9.html",
    isPublic: false,
  },
];
