const POSTS = {
  post: [
    {
      id: "1",
      name: "Name of Poster",
      avatar: "profile/1.jpg",
      location: "A very long location name",
      image: "posts/1.jpg",
      likes: 40,
      comments: 20,
      about: "Lorem Ipsum",
    },
    {
      id: "2",
      name: "Name of Poster",
      avatar: "profile/2.jpg",
      location: "A very long location name",
      image: "posts/2.jpg",
      likes: 40,
      comments: 20,
      about: "",
    },
    {
      id: "3",
      name: "Name of Poster",
      avatar: "profile/3.jpg",
      location: "A very long location name",
      image: "posts/3.jpg",
      likes: 40,
      comments: 20,
      about: "Lorem Ipsum",
    },
    {
      id: "4",
      name: "Name of Poster",
      avatar: "profile/4.jpg",
      location: "A very long location name",
      image: "posts/4.jpg",
      likes: 40,
      comments: 20,
      about: "Lorem Ipsum",
    },
    {
      id: "5",
      name: "Name of Poster",
      avatar: "profile/5.jpg",
      location: "A very long location name",
      image: "posts/5.jpg",
      likes: 40,
      comments: 20,
      about: "Lorem Ipsum",
    },
    {
      id: "6",
      name: "Name of Poster",
      avatar: "profile/6.jpg",
      location: "A very long location name",
      image: "posts/6.jpg",
      likes: 40,
      comments: 20,
      about: "Lorem Ipsum",
    },
  ],
};
export default POSTS;
