const STORIES = {
  stories: [
    {
      id: "1",
      name: "A",
      avatar: "profile/1.jpg",
      story: "posts/1.jpg",
    },
    {
      id: "2",
      name: "B",
      avatar: "profile/2.jpg",
      story: "posts/2.jpg",
    },
    {
      id: "3",
      name: "C",
      avatar: "profile/3.jpg",
      story: "posts/3.jpg",
    },
    {
      id: "4",
      name: "A",
      avatar: "profile/4.jpg",
      story: "posts/4.jpg",
    },
    {
      id: "5",
      name: "B",
      avatar: "profile/5.jpg",
      story: "posts/5.jpg",
    },
    {
      id: "6",
      name: "C",
      avatar: "profile/6.jpg",
      story: "posts/6.jpg",
    },
    {
      id: "7",
      name: "A",
      avatar: "profile/7.jpg",
      story: "posts/7.jpg",
    },
    {
      id: "8",
      name: "B",
      avatar: "profile/8.jpg",
      story: "posts/8.jpg",
    },
    {
      id: "9",
      name: "C",
      avatar: "profile/9.jpg",
      story: "posts/9.jpg",
    },
    {
      id: "1",
      name: "A",
      avatar: "profile/1.jpg",
      story: "posts/1.jpg",
    },
    {
      id: "2",
      name: "B",
      avatar: "profile/2.jpg",
      story: "posts/2.jpg",
    },
    {
      id: "3",
      name: "C",
      avatar: "profile/3.jpg",
      story: "posts/3.jpg",
    },
    {
      id: "4",
      name: "A",
      avatar: "profile/4.jpg",
      story: "posts/4.jpg",
    },
    {
      id: "5",
      name: "B",
      avatar: "profile/5.jpg",
      story: "posts/5.jpg",
    },
    {
      id: "6",
      name: "C",
      avatar: "profile/6.jpg",
      story: "posts/6.jpg",
    },
    {
      id: "7",
      name: "A",
      avatar: "profile/7.jpg",
      story: "posts/7.jpg",
    },
    {
      id: "8",
      name: "B",
      avatar: "profile/8.jpg",
      story: "posts/8.jpg",
    },
    {
      id: "9",
      name: "C",
      avatar: "profile/9.jpg",
      story: "posts/9.jpg",
    },
    {
      id: "1",
      name: "A",
      avatar: "profile/1.jpg",
      story: "posts/1.jpg",
    },
    {
      id: "2",
      name: "B",
      avatar: "profile/2.jpg",
      story: "posts/2.jpg",
    },
    {
      id: "3",
      name: "C",
      avatar: "profile/3.jpg",
      story: "posts/3.jpg",
    },
    {
      id: "4",
      name: "A",
      avatar: "profile/4.jpg",
      story: "posts/4.jpg",
    },
    {
      id: "5",
      name: "B",
      avatar: "profile/5.jpg",
      story: "posts/5.jpg",
    },
    {
      id: "6",
      name: "C",
      avatar: "profile/6.jpg",
      story: "posts/6.jpg",
    },
    {
      id: "7",
      name: "A",
      avatar: "profile/7.jpg",
      story: "posts/7.jpg",
    },
    {
      id: "8",
      name: "B",
      avatar: "profile/8.jpg",
      story: "posts/8.jpg",
    },
    {
      id: "9",
      name: "C",
      avatar: "profile/9.jpg",
      story: "posts/9.jpg",
    },
    {
      id: "1",
      name: "A",
      avatar: "profile/1.jpg",
      story: "posts/1.jpg",
    },
    {
      id: "2",
      name: "B",
      avatar: "profile/2.jpg",
      story: "posts/2.jpg",
    },
    {
      id: "3",
      name: "C",
      avatar: "profile/3.jpg",
      story: "posts/3.jpg",
    },
    {
      id: "4",
      name: "A",
      avatar: "profile/4.jpg",
      story: "posts/4.jpg",
    },
    {
      id: "5",
      name: "B",
      avatar: "profile/5.jpg",
      story: "posts/5.jpg",
    },
    {
      id: "6",
      name: "C",
      avatar: "profile/6.jpg",
      story: "posts/6.jpg",
    },
    {
      id: "7",
      name: "A",
      avatar: "profile/7.jpg",
      story: "posts/7.jpg",
    },
    {
      id: "8",
      name: "B",
      avatar: "profile/8.jpg",
      story: "posts/8.jpg",
    },
    {
      id: "9",
      name: "C",
      avatar: "profile/9.jpg",
      story: "posts/9.jpg",
    },
  ],
};
export default STORIES;
