export const STORIES = [
  {
    id: "1",
    profileId: "1",
    name: "A",
    avatar: "profile/1.jpg",
    story: "posts/1.jpg",
    views: 40,
    time: "3h",
  },
  {
    id: "2",
    profileId: "2",
    name: "B",
    avatar: "profile/2.jpg",
    story: "posts/2.jpg",
    views: 30,
    time: "3h",
  },
  {
    id: "3",
    profileId: "3",
    name: "C",
    avatar: "profile/3.jpg",
    story: "posts/3.jpg",
    views: 20,
    time: "3h",
  },
  {
    id: "4",
    profileId: "4",
    name: "A",
    avatar: "profile/4.jpg",
    story: "posts/4.jpg",
    views: 35,
    time: "3h",
  },
  {
    id: "5",
    profileId: "5",
    name: "B",
    avatar: "profile/5.jpg",
    story: "posts/5.jpg",
    views: 50,
    time: "3h",
  },
  {
    id: "6",
    profileId: "6",
    name: "C",
    avatar: "profile/6.jpg",
    story: "posts/6.jpg",
    views: 60,
    time: "3h",
  },
  {
    id: "7",
    profileId: "7",
    name: "A",
    avatar: "profile/7.jpg",
    story: "posts/7.jpg",
    views: 50,
    time: "3m",
  },
  {
    id: "8",
    profileId: "8",
    name: "B",
    avatar: "profile/8.jpg",
    story: "posts/8.jpg",
    views: 50,
    time: "3m",
  },
  {
    id: "9",
    profileId: "9",
    name: "C",
    avatar: "profile/9.jpg",
    story: "posts/9.jpg",
    views: 50,
    time: "3m",
  },
  {
    id: "10",
    profileId: "1",
    name: "A",
    avatar: "profile/1.jpg",
    story: "posts/4.jpg",
    views: 40,
    time: "3h",
  },
  {
    id: "11",
    profileId: "2",
    name: "B",
    avatar: "profile/2.jpg",
    story: "posts/2.jpg",
    views: 30,
    time: "3h",
  },
  {
    id: "12",
    profileId: "3",
    name: "C",
    avatar: "profile/3.jpg",
    story: "posts/3.jpg",
    views: 20,
    time: "3h",
  },
  {
    id: "13",
    profileId: "4",
    name: "A",
    avatar: "profile/4.jpg",
    story: "posts/4.jpg",
    views: 35,
    time: "3h",
  },
  {
    id: "14",
    profileId: "5",
    name: "B",
    avatar: "profile/5.jpg",
    story: "posts/5.jpg",
    views: 50,
    time: "3h",
  },
  {
    id: "15",
    profileId: "6",
    name: "C",
    avatar: "profile/6.jpg",
    story: "posts/6.jpg",
    views: 60,
    time: "3h",
  },
  {
    id: "16",
    profileId: "7",
    name: "A",
    avatar: "profile/7.jpg",
    story: "posts/7.jpg",
    views: 50,
    time: "3m",
  },
  {
    id: "17",
    profileId: "8",
    name: "B",
    avatar: "profile/8.jpg",
    story: "posts/8.jpg",
    views: 50,
    time: "3m",
  },
  {
    id: "18",
    profileId: "9",
    name: "C",
    avatar: "profile/9.jpg",
    story: "posts/9.jpg",
    views: 50,
    time: "3m",
  },
  {
    id: "19",
    profileId: "1",
    name: "A",
    avatar: "profile/1.jpg",
    story: "posts/10.jpg",
    views: 40,
    time: "3h",
  },
  {
    id: "20",
    profileId: "2",
    name: "B",
    avatar: "profile/2.jpg",
    story: "posts/2.jpg",
    views: 30,
    time: "3h",
  },
  {
    id: "21",
    profileId: "3",
    name: "C",
    avatar: "profile/3.jpg",
    story: "posts/3.jpg",
    views: 20,
    time: "3h",
  },
  {
    id: "22",
    profileId: "4",
    name: "A",
    avatar: "profile/4.jpg",
    story: "posts/4.jpg",
    views: 35,
    time: "3h",
  },
  {
    id: "23",
    profileId: "5",
    name: "B",
    avatar: "profile/5.jpg",
    story: "posts/5.jpg",
    views: 50,
    time: "3h",
  },
  {
    id: "24",
    profileId: "6",
    name: "C",
    avatar: "profile/6.jpg",
    story: "posts/6.jpg",
    views: 60,
    time: "3h",
  },
  {
    id: "25",
    profileId: "7",
    name: "A",
    avatar: "profile/7.jpg",
    story: "posts/7.jpg",
    views: 50,
    time: "3m",
  },
  {
    id: "26",
    profileId: "8",
    name: "B",
    avatar: "profile/8.jpg",
    story: "posts/8.jpg",
    views: 50,
    time: "3m",
  },
  {
    id: "27",
    profileId: "9",
    name: "C",
    avatar: "profile/9.jpg",
    story: "posts/9.jpg",
    views: 50,
    time: "3m",
  },
];
