const STORIES = [
  {
    id: "1",
    name: "A",
    avatar: "profile/1.jpg",
    story: "posts/1.jpg",
    views: 40,
    time: "3h",
  },
  {
    id: "2",
    name: "B",
    avatar: "profile/2.jpg",
    story: "posts/2.jpg",
    views: 30,
    time: "3h",
  },
  {
    id: "3",
    name: "C",
    avatar: "profile/3.jpg",
    story: "posts/3.jpg",
    views: 20,
    time: "3h",
  },
  {
    id: "4",
    name: "A",
    avatar: "profile/4.jpg",
    story: "posts/4.jpg",
    views: 35,
    time: "3h",
  },
  {
    id: "5",
    name: "B",
    avatar: "profile/5.jpg",
    story: "posts/5.jpg",
    views: 50,
    time: "3h",
  },
  {
    id: "6",
    name: "C",
    avatar: "profile/6.jpg",
    story: "posts/6.jpg",
    views: 60,
    time: "3h",
  },
  {
    id: "7",
    name: "A",
    avatar: "profile/7.jpg",
    story: "posts/7.jpg",
    views: 50,
    time: "3m",
  },
  {
    id: "8",
    name: "B",
    avatar: "profile/8.jpg",
    story: "posts/8.jpg",
    views: 50,
    time: "3m",
  },
  {
    id: "9",
    name: "C",
    avatar: "profile/9.jpg",
    story: "posts/9.jpg",
    views: 50,
    time: "3m",
  },
  {
    id: "1",
    name: "A",
    avatar: "profile/1.jpg",
    story: "posts/1.jpg",
    views: 40,
    time: "3h",
  },
  {
    id: "2",
    name: "B",
    avatar: "profile/2.jpg",
    story: "posts/2.jpg",
    views: 30,
    time: "3h",
  },
  {
    id: "3",
    name: "C",
    avatar: "profile/3.jpg",
    story: "posts/3.jpg",
    views: 20,
    time: "3h",
  },
  {
    id: "4",
    name: "A",
    avatar: "profile/4.jpg",
    story: "posts/4.jpg",
    views: 35,
    time: "3h",
  },
  {
    id: "5",
    name: "B",
    avatar: "profile/5.jpg",
    story: "posts/5.jpg",
    views: 50,
    time: "3h",
  },
  {
    id: "6",
    name: "C",
    avatar: "profile/6.jpg",
    story: "posts/6.jpg",
    views: 60,
    time: "3h",
  },
  {
    id: "7",
    name: "A",
    avatar: "profile/7.jpg",
    story: "posts/7.jpg",
    views: 50,
    time: "3m",
  },
  {
    id: "8",
    name: "B",
    avatar: "profile/8.jpg",
    story: "posts/8.jpg",
    views: 50,
    time: "3m",
  },
  {
    id: "9",
    name: "C",
    avatar: "profile/9.jpg",
    story: "posts/9.jpg",
    views: 50,
    time: "3m",
  },
  {
    id: "1",
    name: "A",
    avatar: "profile/1.jpg",
    story: "posts/1.jpg",
    views: 40,
    time: "3h",
  },
  {
    id: "2",
    name: "B",
    avatar: "profile/2.jpg",
    story: "posts/2.jpg",
    views: 30,
    time: "3h",
  },
  {
    id: "3",
    name: "C",
    avatar: "profile/3.jpg",
    story: "posts/3.jpg",
    views: 20,
    time: "3h",
  },
  {
    id: "4",
    name: "A",
    avatar: "profile/4.jpg",
    story: "posts/4.jpg",
    views: 35,
    time: "3h",
  },
  {
    id: "5",
    name: "B",
    avatar: "profile/5.jpg",
    story: "posts/5.jpg",
    views: 50,
    time: "3h",
  },
  {
    id: "6",
    name: "C",
    avatar: "profile/6.jpg",
    story: "posts/6.jpg",
    views: 60,
    time: "3h",
  },
  {
    id: "7",
    name: "A",
    avatar: "profile/7.jpg",
    story: "posts/7.jpg",
    views: 50,
    time: "3m",
  },
  {
    id: "8",
    name: "B",
    avatar: "profile/8.jpg",
    story: "posts/8.jpg",
    views: 50,
    time: "3m",
  },
  {
    id: "9",
    name: "C",
    avatar: "profile/9.jpg",
    story: "posts/9.jpg",
    views: 50,
    time: "3m",
  },
  {
    id: "1",
    name: "A",
    avatar: "profile/1.jpg",
    story: "posts/1.jpg",
    views: 40,
    time: "3m",
  },
  {
    id: "2",
    name: "B",
    avatar: "profile/2.jpg",
    story: "posts/2.jpg",
    views: 30,
    time: "3m",
  },
  {
    id: "3",
    name: "C",
    avatar: "profile/3.jpg",
    story: "posts/3.jpg",
    views: 20,
    time: "3m",
  },
  {
    id: "4",
    name: "A",
    avatar: "profile/4.jpg",
    story: "posts/4.jpg",
    views: 35,
    time: "3m",
  },
  {
    id: "5",
    name: "B",
    avatar: "profile/5.jpg",
    story: "posts/5.jpg",
    views: 50,
    time: "3m",
  },
  {
    id: "6",
    name: "C",
    avatar: "profile/6.jpg",
    story: "posts/6.jpg",
    views: 60,
    time: "3m",
  },
  {
    id: "7",
    name: "A",
    avatar: "profile/7.jpg",
    story: "posts/7.jpg",
    views: 50,
    time: "3m",
  },
  {
    id: "8",
    name: "B",
    avatar: "profile/8.jpg",
    story: "posts/8.jpg",
    views: 50,
    time: "3m",
  },
  {
    id: "9",
    name: "C",
    avatar: "profile/9.jpg",
    story: "posts/9.jpg",
    views: 50,
    time: "3m",
  },
];
export default STORIES;
